tmux:
  symbols:
    branch: ''
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: '●'
    conflict: '✖'
    modified: '+'
    untracked: '…'
    stashed: '⚑'
    clean: '✔'
  styles:
    clear: '#[fg=default]'
    state: '#[fg=red,bold]'
    branch: '#[fg={{color4}},bold]'
    remote: '#[fg={{color5}}]'
    staged: '#[fg=green,bold]'
    conflict: '#[fg=red,bold]'
    modified: '#[fg={{color5}},bold]'
    untracked: '#[fg={{color4}}]'
    stashed: '#[fg={{color5}},bold]'
    clean: '#[fg=green,bold]'
  layout: [branch, ' ', remote, ' ', flags]
  options:
    branch_max_len: 20
