tmux:
  symbols:
    branch: ''
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: '●'
    conflict: '✖'
    modified: '+'
    untracked: '…'
    stashed: '⚑'
    clean: '✔'
  styles:
    clear: '#[fg=default]'
    state: '#[fg=red,bold]'
    branch: '#[fg=#959D91,bold]'
    remote: '#[fg=#9FA196]'
    staged: '#[fg=green,bold]'
    conflict: '#[fg=red,bold]'
    modified: '#[fg=#9FA196,bold]'
    untracked: '#[fg=#959D91]'
    stashed: '#[fg=#9FA196,bold]'
    clean: '#[fg=green,bold]'
  layout: [branch, ' ', remote, ' ', flags]
  options:
    branch_max_len: 20
