tmux:
  symbols:
    branch: ''
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: '●'
    conflict: '✖'
    modified: '+'
    untracked: '…'
    stashed: '⚑'
    clean: '✔'
  styles:
    clear: '#[fg=default]'
    state: '#[fg=red,bold]'
    branch: '#[fg=colour62,bold]'
    remote: '#[fg=colour99]'
    staged: '#[fg=green,bold]'
    conflict: '#[fg=red,bold]'
    modified: '#[fg=colour99,bold]'
    untracked: '#[fg=colour62]'
    stashed: '#[fg=colour99,bold]'
    clean: '#[fg=green,bold]'
  layout: [branch, ' ', remote, ' ', flags]
  options:
    branch_max_len: 20
