$background = rgb(191717)
$foreground = rgb(F1F3ED)
$color0 = rgb(403E3E)
$color1 = rgb(7F877C)
$color2 = rgb(AA8673)
$color3 = rgb(AE9078)
$color4 = rgb(959D91)
$color5 = rgb(9FA196)
$color6 = rgb(A1A599)
$color7 = rgb(E2E5DD)
$color8 = rgb(9EA09B)
$color9 = rgb(AAB4A5)
$color10 = rgb(E2B399)
$color11 = rgb(E8C0A1)
$color12 = rgb(C7D1C2)
$color13 = rgb(D4D7C8)
$color14 = rgb(D6DCCC)
$color15 = rgb(E2E5DD)
