$background = rgb(111218)
$foreground = rgb(F9F1FF)
$color0 = rgb(393A40)
$color1 = rgb(1D6997)
$color2 = rgb(216D97)
$color3 = rgb(277FA5)
$color4 = rgb(956D9A)
$color5 = rgb(52A4B2)
$color6 = rgb(B1A0BF)
$color7 = rgb(EDE2F7)
$color8 = rgb(A69EAD)
$color9 = rgb(278CC9)
$color10 = rgb(2B91CA)
$color11 = rgb(34A9DC)
$color12 = rgb(C692CE)
$color13 = rgb(6DDAED)
$color14 = rgb(EDD6FF)
$color15 = rgb(EDE2F7)
