$timeout_warning = 480      # 8 minutes - warning notification
$timeout_dim = 600          # 10 minutes - dim screen & keyboard backlight off
$timeout_lock = 900         # 15 minutes - lock screen
$timeout_screen_off = 1200  # 20 minutes - turn off display
$timeout_suspend = 1800     # 30 minutes - suspend system

general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# Warn before dim
listener {
    timeout = $timeout_warning
    on-timeout = notify-send "Getting sleepy..." "Screen will dim in 2 minutes" -u low
}

# Dim the screen
listener {
    timeout = $timeout_dim
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Turn off keyboard backlight
listener {
    timeout = $timeout_dim
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# Lock the screen
listener {
    timeout = $timeout_lock
    on-timeout = loginctl lock-session
}

# Turn off the monitor
listener {
    timeout = $timeout_screen_off
    on-timeout = hyprctl dispatch dpms off 
    on-resume = hyprctl dispatch dpms on
}

# Suspend system
# listener {
#     timeout = $timeout_suspend
#     on-timeout = systemctl suspend
# }
