theme[main_bg]="{{ colors.surface.default.hex }}"
theme[main_fg]="{{ colors.on_surface.default.hex }}"

theme[title]="{{ colors.on_surface.default.hex }}"
theme[hi_fg]="{{ colors.secondary.default.hex }}"
theme[selected_bg]="{{ colors.secondary.default.hex }}"
theme[selected_fg]="{{ colors.on_surface.default.hex }}"
theme[inactive_fg]="{{ colors.surface_variant.default.hex }}"
theme[graph_text]="{{ colors.on_surface.default.hex }}"
theme[meter_bg]="{{ colors.surface_variant.default.hex }}"
theme[proc_misc]="{{ colors.primary_fixed.default.hex }}"
theme[cpu_box]="{{ colors.primary_fixed.default.hex }}"
theme[mem_box]="{{ colors.tertiary_fixed.default.hex }}"
theme[net_box]="{{ colors.error.default.hex }}"
theme[proc_box]="{{ colors.primary.default.hex }}"
theme[div_line]="{{ colors.surface_variant.default.hex }}"

theme[temp_start]="{{ colors.primary_fixed.default.hex }}"
theme[temp_mid]="{{ colors.on_secondary_fixed_variant.default.hex }}"
theme[temp_end]="{{ colors.on_tertiary_fixed_variant.default.hex }}"

theme[cpu_start]="{{ colors.primary_fixed.default.hex }}"
theme[cpu_mid]="{{ colors.on_secondary_fixed_variant.default.hex }}"
theme[cpu_end]="{{ colors.on_tertiary_fixed_variant.default.hex }}"

theme[free_start]="{{ colors.tertiary_fixed.default.hex }}"
theme[free_mid]="{{ colors.tertiary_fixed.default.hex }}"
theme[free_end]="{{ colors.tertiary.default.hex }}"

theme[cached_start]="{{ colors.tertiary_fixed.default.hex }}"
theme[cached_mid]="{{ colors.tertiary_fixed.default.hex }}"
theme[cached_end]="{{ colors.tertiary.default.hex }}"

theme[available_start]="{{ colors.tertiary_fixed.default.hex }}"
theme[available_mid]="{{ colors.tertiary_fixed.default.hex }}"
theme[available_end]="{{ colors.tertiary.default.hex }}"

theme[used_start]="{{ colors.tertiary_fixed.default.hex }}"
theme[used_mid]="{{ colors.tertiary_fixed.default.hex }}"
theme[used_end]="{{ colors.tertiary.default.hex }}"

theme[download_start]="{{ colors.error.default.hex }}"
theme[download_mid]="{{ colors.error_container.default.hex }}"
theme[download_end]="{{ colors.error_container.default.hex }}"

theme[upload_start]="{{ colors.tertiary_container.default.hex }}"
theme[upload_mid]="{{ colors.secondary_container.default.hex }}"
theme[upload_end]="{{ colors.primary_container.default.hex }}"

theme[process_start]="{{ colors.primary.default.hex }}"
theme[process_mid]="{{ colors.secondary.default.hex }}"
theme[process_end]="{{ colors.surface_container_highest.default.hex }}"
