tmux:
  symbols:
    branch: ''
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: '●'
    conflict: '✖'
    modified: '+'
    untracked: '…'
    stashed: '⚑'
    clean: '✔'
  styles:
    clear: '#[fg=default]'
    state: '#[fg={{ colors.error.default.hex }},bold]'
    branch: '#[fg={{ colors.primary.default.hex }},bold]'
    remote: '#[fg={{ colors.tertiary.default.hex }}]'
    staged: '#[fg={{ colors.tertiary_fixed.default.hex }},bold]'
    conflict: '#[fg={{ colors.error.default.hex }},bold]'
    modified: '#[fg={{ colors.secondary.default.hex }},bold]'
    untracked: '#[fg={{ colors.on_surface_variant.default.hex }}]'
    stashed: '#[fg={{ colors.secondary_fixed_dim.default.hex }},bold]'
    clean: '#[fg={{ colors.tertiary_fixed.default.hex }},bold]'
  layout: [branch, ' ', remote, ' ', flags]
  options:
    branch_max_len: 20
