$hl_background = rgba({{ colors.surface.default.hex | replace: "#", "" }}ff)
$hl_foreground = rgba({{ colors.on_surface.default.hex | replace: "#", "" }}ff)
$hl_color0 = rgba({{ colors.surface_container_highest.default.hex | replace: "#", "" }}ff)
$hl_color1 = rgba({{ colors.error.default.hex | replace: "#", "" }}ff)
$hl_color2 = rgba({{ colors.tertiary.default.hex | replace: "#", "" }}ff)
$hl_color3 = rgba({{ colors.secondary.default.hex | replace: "#", "" }}ff)
$hl_color4 = rgba({{ colors.primary.default.hex | replace: "#", "" }}ff)
$hl_color5 = rgba({{ colors.primary_fixed.default.hex | replace: "#", "" }}ff)
$hl_color6 = rgba({{ colors.tertiary_fixed.default.hex | replace: "#", "" }}ff)
$hl_color7 = rgba({{ colors.on_surface.default.hex | replace: "#", "" }}ff)
$hl_color8 = rgba({{ colors.surface_variant.default.hex | replace: "#", "" }}ff)
$hl_color9 = rgba({{ colors.primary_container.default.hex | replace: "#", "" }}ff)
$hl_color10 = rgba({{ colors.tertiary_container.default.hex | replace: "#", "" }}ff)
$hl_color11 = rgba({{ colors.secondary_container.default.hex | replace: "#", "" }}ff)
$hl_color12 = rgba({{ colors.primary.default.hex | replace: "#", "" }}ff)
$hl_color13 = rgba({{ colors.tertiary.default.hex | replace: "#", "" }}ff)
$hl_color14 = rgba({{ colors.secondary.default.hex | replace: "#", "" }}ff)
$hl_color15 = rgba({{ colors.on_surface_variant.default.hex | replace: "#", "" }}ff)
