return {
  background = "{{ colors.surface.default.hex }}",
  foreground = "{{ colors.on_surface.default.hex }}",
  cursor = "{{ colors.primary.default.hex }}",
  color0 = "{{ colors.surface_container_highest.default.hex }}",
  color1 = "{{ colors.error.default.hex }}",
  color2 = "{{ colors.tertiary.default.hex }}",
  color3 = "{{ colors.secondary.default.hex }}",
  color4 = "{{ colors.primary.default.hex }}",
  color5 = "{{ colors.primary_fixed.default.hex }}",
  color6 = "{{ colors.tertiary_fixed.default.hex }}",
  color7 = "{{ colors.on_surface.default.hex }}",
  color8 = "{{ colors.surface_variant.default.hex }}",
  color9 = "{{ colors.primary_container.default.hex }}",
  color10 = "{{ colors.tertiary_container.default.hex }}",
  color11 = "{{ colors.secondary_container.default.hex }}",
  color12 = "{{ colors.primary.default.hex }}",
  color13 = "{{ colors.tertiary.default.hex }}",
  color14 = "{{ colors.secondary.default.hex }}",
  color15 = "{{ colors.on_surface_variant.default.hex }}",
}
