$hl_background = rgba({{background | strip}}ff)
$hl_foreground = rgba({{foreground | strip}}ff)
$hl_color0 = rgba({{color0 | strip}}ff)
$hl_color1 = rgba({{color1 | strip}}ff)
$hl_color2 = rgba({{color2 | strip}}ff)
$hl_color3 = rgba({{color3 | strip}}ff)
$hl_color4 = rgba({{color4 | strip}}ff)
$hl_color5 = rgba({{color5 | strip}}ff)
$hl_color6 = rgba({{color6 | strip}}ff)
$hl_color7 = rgba({{color7 | strip}}ff)
$hl_color8 = rgba({{color8 | strip}}ff)
$hl_color9 = rgba({{color9 | strip}}ff)
$hl_color10 = rgba({{color10 | strip}}ff)
$hl_color11 = rgba({{color11 | strip}}ff)
$hl_color12 = rgba({{color12 | strip}}ff)
$hl_color13 = rgba({{color13 | strip}}ff)
$hl_color14 = rgba({{color14 | strip}}ff)
$hl_color15 = rgba({{color15 | strip}}ff)
