decoration {
    rounding = 10
    active_opacity = 1 # 0.8
    inactive_opacity = 0.80
    fullscreen_opacity = 1

    blur {
        enabled = yes
        size = 5
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }

    shadow {
        enabled= true
        ignore_window = true
        range = 4
        offset = 2 2
        render_power = 2
        color = 0x66000000
    }

}



# Blur for wlogout background
layerrule = blur on, match:namespace logout_dialog




# Blur waybar
# layerrule = blur on, match:namespace waybar
# Blur wlogout
# layerrule = blur on, match:namespace logout_dialog
# Blur swaync
# layerrule = blur on, match:namespace swaync-control-center
# layerrule = blur on, match:namespace swaync-notification-window
# layerrule = ignore_zero on, match:namespace swaync-control-center
# layerrule = ignore_zero on, match:namespace swaync-notification-window
# layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
# layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window
