exec-once = waybar # top/bottom bar
exec-once = swww-daemon # wallpaper
exec-once = hypridle # screen lock if idle

# Setup clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = flatpak run org.telegram.desktop  -startintray
exec-once = flatpak run com.discordapp.Discord --start-minimized
