input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options =grp:win_space_toggle
    kb_rules =

    numlock_by_default = true

    follow_mouse = 1
    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat

    # Key repeat (fast like Windows/macOS on minimum)
    repeat_rate = 50  # keys per second when held
    repeat_delay = 250  # ms before repeat starts

    touchpad {
        natural_scroll = true
    }
}
