general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2
    col.active_border = $color12 $color11 45deg
    col.inactive_border = $color0
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}
