foreground         #F1F3ED
background         #191717
cursor             #EAD3C3

active_tab_foreground     #191717
active_tab_background     #F1F3ED
inactive_tab_foreground   #F1F3ED
inactive_tab_background   #191717

active_border_color   #F1F3ED
inactive_border_color #191717
bell_border_color     #7F877C

color0      #403E3E
color1		#7F877C
color2		#AA8673
color3		#AE9078
color4		#959D91
color5		#9FA196
color6		#A1A599
color7		#E2E5DD
color8		#9EA09B
color9		#AAB4A5
color10		#E2B399
color11		#E8C0A1
color12		#C7D1C2
color13		#D4D7C8
color14		#D6DCCC
color15		#E2E5DD
