foreground         #F9F1FF
background         #111218
cursor             #92C1E4

active_tab_foreground     #111218
active_tab_background     #F9F1FF
inactive_tab_foreground   #F9F1FF
inactive_tab_background   #111218

active_border_color   #F9F1FF
inactive_border_color #111218
bell_border_color     #1D6997

color0      #393A40
color1		#1D6997
color2		#216D97
color3		#277FA5
color4		#956D9A
color5		#52A4B2
color6		#B1A0BF
color7		#EDE2F7
color8		#A69EAD
color9		#278CC9
color10		#2B91CA
color11		#34A9DC
color12		#C692CE
color13		#6DDAED
color14		#EDD6FF
color15		#EDE2F7

background_opacity 0.8
